language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update || true
    - composer install --dev --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover


after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
